# Generated by Django 4.2.4 on 2023-09-09 14:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import grade.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(default='Irbid', max_length=30)),
                ('district', models.CharField(default='Al-Kourah', max_length=30)),
                ('neighborhood', models.CharField(default='KufrAwan', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=100)),
                ('exam_top_mark', models.IntegerField()),
                ('exam_pass_mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True, validators=[grade.models.validate_digit_length])),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('national_id', models.CharField(max_length=10, null=True, unique=True, validators=[grade.models.validate_digit_length], verbose_name='national id')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.grade')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.group')),
                ('mobile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.phone')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.section')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNoteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(max_length=50)),
                ('tag', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info')], default='', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.grade')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=500)),
                ('note_date', models.DateField(auto_now=True)),
                ('visible_to_student', models.BooleanField(default=False)),
                ('note_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.studentnotetype')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.student')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.subjectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('note_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.studentnotetype')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateField(auto_now_add=True)),
                ('visible_to_student', models.BooleanField(default=False)),
                ('participation_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.participationoption')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.studentnotetype')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.grade')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_mark', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.examtype')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.student')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_date', models.DateField(auto_now=True)),
                ('absence_reason', models.CharField(default='', max_length=225)),
                ('absence_acceptance', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.student')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkNote',
            fields=[
                ('studentnote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grade.studentnote')),
                ('homeWork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.homework')),
            ],
            bases=('grade.studentnote',),
        ),
    ]
