# Generated by Django 4.2.4 on 2023-09-16 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('student', 'absence_date')},
        ),
    ]
