# Generated by Django 4.2.4 on 2023-09-16 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_alter_participation_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilloption',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.studentnotetype'),
        ),
    ]
