# Generated by Django 3.2.6 on 2021-08-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20210817_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnote',
            name='note_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.studentnotetype'),
        ),
    ]
