# Generated by Django 4.2.4 on 2023-09-16 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0004_skillnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillnote',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
