# Generated by Django 4.2.4 on 2023-09-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0005_skillnote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillnote',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='skillnote',
            unique_together={('student', 'skill')},
        ),
    ]
