# Generated by Django 4.2.4 on 2023-09-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0006_alter_skillnote_date_alter_skillnote_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilloption',
            options={'ordering': ['value']},
        ),
        migrations.AddField(
            model_name='skilloption',
            name='value',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
