# Generated by Django 3.2.6 on 2021-08-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0007_alter_student_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
