# Generated by Django 3.2.6 on 2021-08-22 14:02

from django.db import migrations, models
import grade.models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0008_alter_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnote',
            name='visible_to_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[grade.models.validate_digit_length], verbose_name='national id'),
        ),
    ]
