# Generated by Django 3.2.6 on 2021-08-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0009_auto_20210822_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotetype',
            name='tag',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info')], default='', max_length=10, null=True),
        ),
    ]
