# Generated by Django 3.2.7 on 2021-09-04 16:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import grade.models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0011_auto_20210825_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammark',
            name='exam_mark',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='exammark',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.examtype'),
        ),
    ]
