# Generated by Django 3.2.7 on 2021-09-05 14:00

from django.db import migrations, models
import django.db.models.deletion
import grade.models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0013_alter_exammark_exam_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(default='Irbid', max_length=30)),
                ('district', models.CharField(default='Al-Kourah', max_length=30)),
                ('neighborhood', models.CharField(default='KufrAwan', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True, validators=[grade.models.validate_digit_length])),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.phone'),
        ),
    ]
