# Generated by Django 3.2.7 on 2021-09-13 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0014_auto_20210905_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grade.group'),
        ),
    ]
