# Generated by Django 4.2.4 on 2023-08-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0016_alter_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='participation_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('note_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.studentnotetype')),
            ],
        ),
    ]
