# Generated by Django 4.2.4 on 2023-08-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0017_participation_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='participation_option',
            new_name='ParticipationOption',
        ),
    ]
