# Generated by Django 4.2.4 on 2023-08-29 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0018_rename_participation_option_participationoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentnotetype',
            old_name='NoteType',
            new_name='note_type',
        ),
    ]
